### ISSUE TITLE
How to add a global variable to the env?

### ISSUE THREAD

**Issue by moruzerinho6** [Teoxoy/lua-in-js#10]
First thanks for making this lib, can't really guess how I would make something like this myself.

I'm trying to add a global variable which is a table but I'm having no luck doing it.

Lua Code Example:

```Lua
Trace = lua.Trace
Warn = lua.Warn

MersenneTwister = { Random=math.random, Seed=math.randomseed }

PLAYER_1 = "PlayerNumber_P1"
PLAYER_2 = "PlayerNumber_P2"
NUM_PLAYERS = #PlayerNumber
```

The problem I'm having is with trying to add `PlayerNumber` as the file I'm executing expects it to be a defined global. It was trivial to add `lua.Trace` and `lua.Warn` with the documentation provided at the readme, I simply did was such bellow

```JavaScript
const luaAdditional = new luainjs.Table({
	Trace: (msg) => {
		console.log(msg)
	},
	Warn: (msg) => {		
		console.warn(msg)
	}
})
luaEnv.loadLib('lua', luaAdditional)
```

However, I can't find exactly how I could add a global table, I've tried adding it to the global variable directly such as

```JavaScript
const globalEnv = new luainjs.Table({
	PlayerNumber: new luainjs.Table({ '1': 'PlayerNumber_P1' })
})
luaEnv.loadLib('_G', globalEnv)
```

And it did not work, I tried looking at what the table gets transformed into lua-side and also tried this:

```JavaScript
const globalEnv = new luainjs.Table({
	keys: [1, 2],
	values: ['PlayerNumber_P1', 'PlayerNumber_P2']
})
luaEnv.loadLib('PlayerNumber', globalEnv)
```

But whatever I added as argument to the Table method would always be inside `srtValues`.

Given my failed attempts, how could I add a `PlayerNumber` table as a global to the file I parse?

Here's the result I'm trying to reach:

![image](https://github.com/teoxoy/lua-in-js/assets/58047457/3beb1e7b-d4e4-41dc-bd68-08b8d3676402)

**Comment by teoxoy** [comment]
Looking at the `Table` constructor, I think this should work:

```js
luaEnv.loadLib('PlayerNumber', new luainjs.Table(['PlayerNumber_P1', 'PlayerNumber_P2']))
```

since you seem to want it to be an array and lua uses Tables for both dictionaries and arrays.

**Comment by moruzerinho6** [comment]
That does indeed work, thanks for your help! I'm honestly not sure how I didn't try this.

As for an unrelated question, is it possible for me to somehow get the global env after a file has been parser and apply that global env to another file to be parsed?

The reason for this is because I have a whole list of files that are meant to populate the global env with many variables/functions and then other files are meant to use them, I'm aware I could add those js-side myself but I'd like to ask anyway.

Thanks again.

**Comment by teoxoy** [comment]
Happy to help :)

> As for an unrelated question, is it possible for me to somehow get the global env after a file has been parser and apply that global env to another file to be parsed?

IIRC the env is persistent, so if you parse and execute, changes to the global env should be present in other files

**Comment by moruzerinho6** [comment]
It seems that's indeed the case, thank you very much, closing this.
