### ISSUE TITLE
Logical operators evaluate left-hand side twice

### ISSUE THREAD

**Issue by Sophos-Elias-Vasylenko** [teoxoy/lua-in-js#16]
For context, I am using lua-in-js for unit testing redis scripts in node. It mostly works great for this, thanks! However I noticed that mocks were getting called multiple times in some scripts when I didn't think they should be.

Turns out that some logical operators appear to evaluate the LHS twice. This makes sense as it looks as transpilation for them is implemented via simple string substitution: https://github.com/teoxoy/lua-in-js/blob/3d4f9e2865e979d2eb8ef205f666c0852b283eab/src/parser.ts#L306

This should probably be updated to assign the result of `left` to a local variable first, assuming you have some mechanism to maintain hygiene and avoid unintended shadowing? I'm no Lua expert but I think it is not supposed to eval LHS twice. Please correct me if I'm understanding something wrong, I really just glanced over and made a lot of assumptions!

**Comment by teoxoy** [comment]
It does look like the LHS will get evaluated twice.

**Comment by teoxoy** [comment]
Fixed with ca94a68d03c201c30b6da0fd05f376449bcba88d (part of v2.2.4).
