### ISSUE TITLE
Browser version

### ISSUE THREAD

**Issue by Sheepolution** [Teoxoy/lua-in-js#2]
Will there be a browser version, just like with Starlight?

**Comment by Teoxoy** [comment]
It doesn't depend on node neither does it depend on the browser.

Do you have any issues with getting it to work in the browser?

**Comment by Sheepolution** [comment]
Yes, how would I go about doing so? I'm talking about importing it as a `<script type="text/javascript">`.
I found the file `lua-in-js.es.js` but it uses `import` which causes `Uncaught SyntaxError: Cannot use import statement outside a module`.

**Comment by Teoxoy** [comment]
I don't provide a bundle ready to use in the browser.

I could provide a bundle but most people I know use a build system like webpack or rollup.

Do you have any reason to not use a build system?

**Comment by Sheepolution** [comment]
Ah okay. I wasn't aware build systems work like that so that they can make it work for browsers. Cool, I got it working now and I learned something new today. Thanks!

**Comment by Teoxoy** [comment]
There is also parcel bundler which doesn't need any configuration - works well for small to medium size projects.

Glad I helped!
