### ISSUE TITLE
Set lua variable to function that was loaded by javascript?

### ISSUE THREAD

**Issue by penguib** [Teoxoy/lua-in-js#4]
In my Javascript script code I'm loading a class with all of its functions and properties, then returning loading that library. How could I set a lua variable when creating that class. Example:
Javascript:
```js
function newClass(){
    const example = new Class()

    const name = example.name
    const id = example.id

    function changeName(newName) {
        return example.name = newName
    }

    const lib = new luainjs.Table({
        name,
        id,
        changeName
    })

    return luaEnv.loadLib("Example", lib)
}

luaEnv.loadLib("Instance", new luainjs.Table({
    newClass
}))
```
Then in lua I am trying to do:
```lua
    local ex = Instance.newClass()
    print(ex.name,ex.id)
```
Without doing
```lua
    local ex = Instance.newClass()
    print(Example.name,Example.id)
```

**Comment by Teoxoy** [comment]
At the end of the `newClass` function return the table instead of `luaEnv.loadLib("Example", lib)`.

`luaEnv.loadLib` doesn't return anything (`undefined`) and it will get coerced to `nil` in Lua.

**Comment by penguib** [comment]
Thank you, this worked.
