### ISSUE TITLE
When requiring lua files, lua-in-js cannot find the file?

### ISSUE THREAD

**Issue by penguib** [Teoxoy/lua-in-js#5]
I'm trying to require another file and whenever I try to require it, my console errors and tells me that the module is not found. The path the file is located in is: `../node_modules/lua-hill/modules/globals`. I call:
```lua
local mod = require("../node_modules/lua-hill/modules/globals")
```
and then my console spits out: `message: "Module '../node_modules/lua-hill/modules/globals.lua' not found!"`

**Comment by Teoxoy** [comment]
When you create the lua env using `luainjs.createEnv`, pass it an object with `LUA_PATH`, `fileExists` and `loadFile`. These 3 config options are explained in the [readme](https://github.com/Teoxoy/lua-in-js/blob/master/README.md#create-the-lua-environment).

**Comment by penguib** [comment]
I'm using that and I still get an error when requiring modules.
Javascript:
```js
const rootPath = "./node_modules/lua-hill/bin/modules"
const luaEnv = luainjs.createEnv({
    LUA_PATH: rootPath,
    fileExists: p => fs.existsSync(path.join(rootPath, p)),
    loadFile: p => fs.readFileSync(path.join(rootPath, p), {
        encoding: 'utf8'
    }),
})
```
lua:
```lua
local mod = require("meta")
```
I get the error `message: "Module 'meta.lua' not found!"`. `meta` is in the modules folder.

**Comment by Teoxoy** [comment]
`LUA_PATH` is a special kind of path. Here are the [docs](https://www.lua.org/manual/5.3/manual.html#pdf-package.path) for it.

The default value of `LUA_PATH` is `./?.lua`.
If you want to be able to `require("meta")` then, either don't modify `LUA_PATH` or set it: `LUA_PATH: rootPath + '/?.lua'` and in the other 2 functions, you will get the full relative path (i.e. you don't have to join the path with the root one)
